name: Mergeabot

on:
  schedule:
    - cron: "0 0 * * *"

  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  mergeabot:
    runs-on: ubuntu-latest
    steps:
      - uses: freckle/mergeabot-action@f6a000df48d9cfa50928873291f09b9d811e7e45 # v3
        with:
          quarantine-days: -1
